### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by kaykay38**
Collaborated with Kiana Norton @NyahHuh

### CODE REVIEW

**Comment by kaykay38** [comment]
# Assignment

- Pull Request title includes "Assignment 1" in the title ✔
- Pull Request targets Assignment 1 branch ✔
- Issue 1: Application no longer crashes ✔
- Issue 2: Unit test properly passes ✔

### Extra Credit
- Issue 3: Feature request implemented ✔
- Issue 3: Feature request unit tested ✔

**Comment by kaykay38** [comment]
# Assignment

- Pull Request title includes "Assignment 1" in the title ✔
- Pull Request targets Assignment 1 branch ✔
- Issue 1: Application no longer crashes ✔
- Issue 2: Unit test properly passes ✔

### Extra Credit
- Issue 3: Feature request implemented ✔
- Issue 3: Feature request unit tested ✔

**Comment by NyahHuh** [comment]
Assignment
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔
Extra Credit
Issue 3: Feature request implemented ✔
Issue 3: Feature request unit tested ✔

**Comment by breaman** [comment]
Nice work on the assignment. Good approach on the extra credit as well.

**Pull request closed without merging**
